# Generated by Django 2.2.7 on 2020-06-09 11:42

from django.db import migrations, models
import upload_validator


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CarouselImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10), (11, 11), (11, 11), (12, 12), (13, 13), (14, 14), (15, 15), (16, 16), (17, 17), (18, 18), (19, 19), (20, 20)])),
                ('description', models.CharField(max_length=50)),
                ('picture', models.ImageField(upload_to='hello.PictureWrapper/bytes/filename/mimetype')),
            ],
        ),
        migrations.CreateModel(
            name='Officer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10), (11, 11), (11, 11), (12, 12), (13, 13), (14, 14), (15, 15), (16, 16), (17, 17), (18, 18), (19, 19), (20, 20)])),
                ('picture', models.ImageField(upload_to='hello.PictureWrapper/bytes/filename/mimetype')),
                ('name', models.CharField(max_length=40)),
                ('position', models.CharField(max_length=40)),
                ('email', models.EmailField(max_length=40)),
                ('about', models.CharField(help_text='Max 200 Characters', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='PictureWrapper',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bytes', models.BinaryField()),
                ('filename', models.CharField(max_length=255)),
                ('mimetype', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(help_text='FULL FIRST NAME, this is how we pair this entry with previous entries', max_length=20)),
                ('lastname', models.CharField(help_text='Same as previous field; please make sure entry is correct. These are integral to how we match players to their history', max_length=30)),
                ('rating', models.IntegerField(default=1500)),
                ('rating_diff', models.IntegerField(blank=True, default=0)),
                ('last_active', models.DateField(blank=True, default='2000-01-01')),
                ('wins', models.IntegerField(blank=True, default=0)),
                ('losses', models.IntegerField(blank=True, default=0)),
                ('draws', models.IntegerField(blank=True, default=0)),
            ],
        ),
        migrations.CreateModel(
            name='VegaChessEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tournament_date', models.DateField()),
                ('entry', models.FileField(upload_to='hello.PictureWrapper/bytes/filename/mimetype', validators=[upload_validator.FileTypeValidator(allowed_types=['text/plain'])])),
            ],
            options={
                'verbose_name_plural': 'Vega Chess Entries',
            },
        ),
    ]
