# Generated by Django 3.0.2 on 2020-12-05 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='VegaChessEntry',
        ),
        migrations.AddField(
            model_name='player',
            name='lichessUser',
            field=models.CharField(default='', help_text='Lichess username', max_length=20),
        ),
    ]
