# Generated by Django 2.2.7 on 2020-06-05 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='officer',
            name='testField',
            field=models.IntegerField(blank=True, default=47),
        ),
    ]
