# Generated by Django 3.0.2 on 2020-03-01 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='FileModel',
            new_name='OfficerPicture',
        ),
        migrations.AlterField(
            model_name='officer',
            name='picture',
            field=models.ImageField(upload_to='hello.OfficerPicture/bytes/filename/mimetype'),
        ),
    ]
