# Generated by Django 3.0.2 on 2020-03-01 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0002_auto_20200229_2231'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='OfficerPicture',
            new_name='PictureWrapper',
        ),
        migrations.AlterField(
            model_name='carouselimage',
            name='picture',
            field=models.ImageField(upload_to='hello.PictureWrapper/bytes/filename/mimetype'),
        ),
        migrations.AlterField(
            model_name='officer',
            name='picture',
            field=models.ImageField(upload_to='hello.PictureWrapper/bytes/filename/mimetype'),
        ),
    ]
