# Generated by Django 3.0.2 on 2020-03-02 05:40

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0003_auto_20200301_1443'),
    ]

    operations = [
        migrations.CreateModel(
            name='VegaChessEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tournament_date', models.DateField()),
                ('entry', models.FileField(upload_to='media/')),
            ],
        ),
        migrations.RemoveField(
            model_name='player',
            name='name',
        ),
        migrations.AddField(
            model_name='player',
            name='firstname',
            field=models.CharField(default=django.utils.timezone.now, help_text='FULL FIRST NAME, this is how we pair this entry with previous entries', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='player',
            name='last_active',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='player',
            name='lastname',
            field=models.CharField(default='lastname', help_text='Same as previous field; please make sure entry is correct. These are integral to how we match players to their history', max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='player',
            name='rating_diff',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
