# Generated by Django 3.0.2 on 2020-03-03 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0005_auto_20200303_0835'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='draws',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='player',
            name='losses',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='player',
            name='rating_diff',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='player',
            name='wins',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
