# Generated by Django 3.0.2 on 2020-03-09 03:52

import datetime
from django.db import migrations, models
import upload_validator


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0006_auto_20200303_0837'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='games_played',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='player',
            name='last_active',
            field=models.DateField(blank=True, default=datetime.datetime(2020, 3, 8, 20, 52, 26, 842570)),
        ),
        migrations.AlterField(
            model_name='vegachessentry',
            name='entry',
            field=models.FileField(upload_to='hello.PictureWrapper/bytes/filename/mimetype', validators=[upload_validator.FileTypeValidator(allowed_types=['text/plain'])]),
        ),
    ]
