# Generated by Django 2.2.7 on 2020-03-09 03:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0007_auto_20200308_2020'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='last_active',
            field=models.DateField(blank=True, default=datetime.datetime(2020, 3, 8, 20, 51, 57, 960858)),
        ),
        migrations.AlterField(
            model_name='player',
            name='rating',
            field=models.IntegerField(default=1500),
        ),
    ]
