# Generated by Django 3.0.2 on 2020-03-20 04:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0007_auto_20200308_2052'),
        ('hello', '0008_auto_20200308_2051'),
    ]

    operations = [
    ]
