# Generated by Django 3.0.2 on 2020-03-20 04:39

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0009_merge_20200319_2139'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vegachessentry',
            options={'verbose_name_plural': 'vega chess entries'},
        ),
        migrations.AlterField(
            model_name='player',
            name='last_active',
            field=models.DateField(blank=True, default=datetime.datetime(2020, 3, 20, 4, 39, 28, 225340, tzinfo=utc)),
        ),
    ]
