# Generated by Django 2.2.7 on 2020-04-13 02:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0010_auto_20200319_2139'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='last_active',
            field=models.DateField(blank=True, default=datetime.datetime(2020, 4, 12, 19, 18, 15, 747377)),
        ),
    ]
