# Generated by Django 3.0.2 on 2020-04-06 07:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0010_auto_20200319_2139'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='games_played',
        ),
        migrations.AlterField(
            model_name='player',
            name='last_active',
            field=models.DateField(blank=True, default=datetime.datetime(2020, 4, 6, 0, 16, 51, 425499)),
        ),
    ]
