# Generated by Django 3.0.2 on 2020-04-12 05:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0011_auto_20200406_0016'),
    ]

    operations = [
        migrations.CreateModel(
            name='FrontPageText',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(help_text='Max 2000 Characters', max_length=2000)),
            ],
        ),
        migrations.AlterField(
            model_name='player',
            name='last_active',
            field=models.DateField(blank=True, default=datetime.datetime(2020, 4, 11, 22, 26, 39, 786212)),
        ),
    ]
