# Generated by Django 2.2.7 on 2020-04-13 02:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0011_auto_20200412_1918'),
        ('hello', '0012_auto_20200411_2226'),
    ]

    operations = [
    ]
