# Generated by Django 2.2.7 on 2020-04-20 03:06

import datetime
from django.db import migrations, models
import hello.models.VegaChessEntry
import upload_validator


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0014_auto_20200412_1928'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='frontpagetext',
            options={'verbose_name_plural': 'Front Page Text'},
        ),
        migrations.AlterModelOptions(
            name='vegachessentry',
            options={'verbose_name_plural': 'Vega Chess Entries'},
        ),
        migrations.AlterField(
            model_name='player',
            name='last_active',
            field=models.DateField(blank=True, default=datetime.datetime(2020, 4, 19, 20, 6, 28, 858974)),
        ),
        migrations.AlterField(
            model_name='vegachessentry',
            name='entry',
            field=models.FileField(upload_to='hello.PictureWrapper/bytes/filename/mimetype', validators=[upload_validator.FileTypeValidator(allowed_types=['text/plain']), hello.models.VegaChessEntry.validate_vega_chess_entry]),
        ),
    ]
