# Generated by Django 3.0.2 on 2020-04-20 03:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0019_auto_20200419_2022'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='last_active',
            field=models.DateField(blank=True, default=datetime.datetime(2020, 4, 19, 20, 22, 45, 560873)),
        ),
    ]
